### ISSUE TITLE
Documentation & Software Update

### ISSUE THREAD

**Issue by mstaack** [akshar001/Maypole_firmware#1]
So Maypole is shipping,

are there any updates software/documentation wise?

Any quickstart tips/schematics?

cheers
max

**Comment by mstaack** [comment]
thanks @akshar001 

which board did you select? i am using latest arduino with esp32 boards url from espressif.

and how do you set the maypole into programming mode?


cheers max

**Comment by akshar001** [comment]
Select esp32 dev module only.
We have put the TTL logic inside, so just connect all the programmer pins to maypole ( if you don't have maypole with programmer ) and hit upload button!

**Comment by mstaack** [comment]
Ah okay, thought it's programmable by usb. Sure I have a spare arduino uno with which I will try to use as a programmer.

Thanks

**Comment by akshar001** [comment]
You have a maypole with programmer or without one?

**Comment by akshar001** [comment]
@mstaack sorry for replying late, have you get it working, maypoles pins are 3.3V for USB to Serial please use FTDI and run at 3.3V.

You will need to connect DTR, RTS, TX and RX that's it,

of-course 3.3V and GND
